baseURL = 'https://entaroadunexecutar.github.io/CC2024-hugo-universal/'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true
title = 'Club Cyclist 2024 Eschelbronn'

theme = 'hugo-universal-theme'

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# allow html in markdown
[markup.goldmark.renderer]
  unsafe = false

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

#------------------------------------------------------- VEREIN ---------------
[[menu.main]]
    name       = "Verein"
    identifier = "menu.verein"
 #   url        = "/img/template-easy-customize.png"
    weight     = 2

[[menu.main]]
    name       = "Vorstand"
    url        = "/de/verein/vorstand/"
    weight     = 1
    parent     = "menu.verein"

[[menu.main]]
    name       = "Satzung"
    url        = "/de/verein/satzung"
    weight     = 2
    parent     = "menu.verein"

[[menu.main]]
    name       = "Satzung als PDF"
    url        = "https://entaroadunexecutar.github.io/CC2024-hugo-universal/de/verein/satzung.pdf/"
    weight     = 3
    parent     = "menu.verein"

#-------------------------------------------------------  Mitglied werden ------------

[[menu.main]]
    name       = "Mitglied werden"
    identifier = "menu.mitglied"
    url        = "https://entaroadunexecutar.github.io/CC2024-hugo-universal/de/mitglied_werden/cce_mitgliedsantrag.pdf/"
    weight     = 3

#-------------------------------------------------------  Kontakt  ------------

[[menu.main]]
    name       = "Kontakt"
    identifier = "menu.kontakt"
    url        = "/de/Kontakt/Kontakt"
    weight     = 4

#-------------------------------------------------------  Impressum  ------------

[[menu.main]]
    name       = "Impressum"
    identifier = "menu.impressum"
    url        = "/de/Impressum/Impressum"
    weight     = 5


[params]

    defaultKeywords = ["Tour", "Rad"]
    mainSections = ["posts"]
    
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    about_us = "<p>Das radelnde Schreinerdorf und sein Fahradverein.</p>"
    copyright = "Copyright (c) 2024, Club Cyclist 2024 Eschelbronn, alle Rechte vorbehalten."

    # Logo
    disabled_logo = false
    logo_text = "Club Cyclist 2024 - Eschelbronn"

    logo = "Bilder/CCE_Wappen.png"
    logo_small = "Bilder/CCE_Wappen.png"

    dropdown_mouse_over = true

# Enable or disable top bar with social icons
# better disable to prevent a flood of spam-mails
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Kontaktiert uns über kontakt@cc2024-eschelbronn.de</p>
      <p class="hidden-md hidden-lg"><a href="mailto:kontakt@cc2024-eschelbronn.de" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

[params.footer.recent_posts]
    enable = true

[params.recent_posts]
    enable = true
    title = "Beiträge"
#    subtitle = "aktuell Artikel "
    hide_summary = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false